import styles from './Feat.module.css'
const Policy = () => {
    return (
        <div>
            <div className={styles.title}>
                Cookie Policy
            </div>
            <p className={styles.comment}>
                Our website uses cookies through Google Analytics to analyze and improve user behavior on the website. Cookies are small text files that are stored on a user's computer and are automatically generated by web browsers when a user visits a website.
            </p>
            <p className={styles.comment}>
                These cookies collect information about a user's website visit history, IP address, browser type and version, operating system, referrer URL, and user actions and behaviors. This information is used through Google Analytics to analyze website traffic, user behavior, and performance, and to improve the website.
            </p>
            <p className={styles.comment}>
                Cookies do not collect personally identifiable information, and user's personal information is not stored. Users can block or delete cookies through their web browser settings. However, blocking or deleting cookies may limit some functionalities of the website.
            </p>
            <p className={styles.comment}>
                By continuing to use the website, users are considered to consent to this cookie policy.
            </p>
            <p className={styles.comment}>
                This cookie policy may be periodically reviewed and updated, so please check regularly for the latest information.
            </p>
            <p className={styles.comment}>
                If you have any questions, please contact us at the following:
                E-Mail: <a href="mailto:scandocs.web@gmail.com">scandocs.web@gmail.com</a>
            </p>
        </div>
    )

}
export default Policy