import { useState } from "react"
import MultiSelect from "../components/ui/MultiSelect"
const languages = [
    {id:0, value:"afr",	text:"Afrikaans"},
    {id:1, value:"amh",	text:"Amharic"},
    {id:2, value:"ara",	text:"Arabic"},
    {id:3, value:"asm",	text:"Assamese"},
    {id:4, value:"aze",	text:"Azerbaijani"},
    {id:5, value:"aze_cyrl",	text:"Azerbaijani - Cyrillic"},
    {id:6, value:"bel",	text:"Belarusian"},
    {id:7, value:"ben",	text:"Bengali"},
    {id:8, value:"bod",	text:"Tibetan"},
    {id:9, value:"bos",	text:"Bosnian"},
    {id:10, value:"bul",	text:"Bulgarian"},
    {id:11, value:"cat",	text:"Catalan; Valencian"},
    {id:12, value:"ceb",	text:"Cebuano"},
    {id:13, value:"ces",	text:"Czech"},
    {id:14, value:"chi_sim",	text:"Chinese - Simplified"},
    {id:15, value:"chi_tra",	text:"Chinese - Traditional"},
    {id:16, value:"chr",	text:"Cherokee"},
    {id:17, value:"cym",	text:"Welsh"},
    {id:18, value:"dan",	text:"Danish"},
    {id:19, value:"deu",	text:"German"},
    {id:20, value:"dzo",	text:"Dzongkha"},
    {id:21, value:"ell",	text:"Greek, Modern (1453-)"},
    {id:22, value:"eng",	text:"English"},
    {id:23, value:"enm",	text:"English, Middle (1100-1500)"},
    {id:24, value:"epo",	text:"Esperanto"},
    {id:25, value:"est",	text:"Estonian"},
    {id:26, value:"eus",	text:"Basque"},
    {id:27, value:"fas",	text:"Persian"},
    {id:28, value:"fin",	text:"Finnish"},
    {id:29, value:"fra",	text:"French"},
    {id:30, value:"frk",	text:"German Fraktur"},
    {id:31, value:"frm",	text:"French, Middle (ca. 1400-1600)"},
    {id:32, value:"gle",	text:"Irish"},
    {id:33, value:"glg",	text:"Galician"},
    {id:34, value:"grc",	text:"Greek, Ancient (-1453)"},
    {id:35, value:"guj",	text:"Gujarati"},
    {id:36, value:"hat",	text:"Haitian; Haitian Creole"},
    {id:37, value:"heb",	text:"Hebrew"},
    {id:38, value:"hin",	text:"Hindi"},
    {id:39, value:"hrv",	text:"Croatian"},
    {id:40, value:"hun",	text:"Hungarian"},
    {id:41, value:"iku",	text:"Inuktitut"},
    {id:42, value:"ind",	text:"Indonesian"},
    {id:43, value:"isl",	text:"Icelandic"},
    {id:44, value:"ita",	text:"Italian"},
    {id:45, value:"ita_old",	text:"Italian - Old"},
    {id:46, value:"jav",	text:"Javanese"},
    {id:47, value:"jpn",	text:"Japanese"},
    {id:48, value:"kan",	text:"Kannada"},
    {id:49, value:"kat",	text:"Georgian"},
    {id:50, value:"kat_old",	text:"Georgian - Old"},
    {id:51, value:"kaz",	text:"Kazakh"},
    {id:52, value:"khm",	text:"Central Khmer"},
    {id:53, value:"kir",	text:"Kirghiz; Kyrgyz"},
    {id:54, value:"kor",	text:"Korean"},
    {id:55, value:"kur",	text:"Kurdish"},
    {id:56, value:"lao",	text:"Lao"},
    {id:57, value:"lat",	text:"Latin"},
    {id:58, value:"lav",	text:"Latvian"},
    {id:59, value:"lit",	text:"Lithuanian"},
    {id:60, value:"mal",	text:"Malayalam"},
    {id:61, value:"mar",	text:"Marathi"},
    {id:62, value:"mkd",	text:"Macedonian"},
    {id:63, value:"mlt",	text:"Maltese"},
    {id:64, value:"msa",	text:"Malay"},
    {id:65, value:"mya",	text:"Burmese"},
    {id:66, value:"nep",	text:"Nepali"},
    {id:67, value:"nld",	text:"Dutch; Flemish"},
    {id:68, value:"nor",	text:"Norwegian"},
    {id:69, value:"ori",	text:"Oriya"},
    {id:70, value:"pan",	text:"Panjabi; Punjabi"},
    {id:71, value:"pol",	text:"Polish"},
    {id:72, value:"por",	text:"Portuguese"},
    {id:73, value:"pus",	text:"Pushto; Pashto"},
    {id:74, value:"ron",	text:"Romanian; Moldavian; Moldovan"},
    {id:75, value:"rus",	text:"Russian"},
    {id:76, value:"san",	text:"Sanskrit"},
    {id:77, value:"sin",	text:"Sinhala; Sinhalese"},
    {id:78, value:"slk",	text:"Slovak"},
    {id:79, value:"slv",	text:"Slovenian"},
    {id:80, value:"spa",	text:"Spanish; Castilian"},
    {id:81, value:"spa_old",	text:"Spanish; Castilian - Old"},
    {id:82, value:"sqi",	text:"Albanian"},
    {id:83, value:"srp",	text:"Serbian"},
    {id:84, value:"srp_latn",	text:"Serbian - Latin"},
    {id:85, value:"swa",	text:"Swahili"},
    {id:86, value:"swe",	text:"Swedish"},
    {id:87, value:"syr",	text:"Syriac"},
    {id:88, value:"tam",	text:"Tamil"},
    {id:89, value:"tel",	text:"Telugu"},
    {id:90, value:"tgk",	text:"Tajik"},
    {id:91, value:"tgl",	text:"Tagalog"},
    {id:92, value:"tha",	text:"Thai"},
    {id:93, value:"tir",	text:"Tigrinya"},
    {id:94, value:"tur",	text:"Turkish"},
    {id:95, value:"uig",	text:"Uighur; Uyghur"},
    {id:96, value:"ukr",	text:"Ukrainian"},
    {id:97, value:"urd",	text:"Urdu"},
    {id:98, value:"uzb",	text:"Uzbek"},
    {id:99, value:"uzb_cyrl",	text:"Uzbek - Cyrillic"},
    {id:100, value:"vie",	text:"Vietnamese"},
    {id:101, value:"yid",	text:"Yiddish"},
]
const Test = () => {
    const [open, setOpen] = useState(false);
    return (
        <>
            <button onClick={()=>setOpen(!open)}>open</button>
            <MultiSelect options={languages} onChange={(result) => console.log(result)} />
        </>
    )

}
export default Test